### ISSUE TITLE
Maximum call stack size exceeded with latest node

### ISSUE THREAD

**Issue by ericnakagawa** [dwyl/decache#31]
Am using 4.1.0 on Mac
Node version 8.5.0

            mod.children.forEach(function (child) {
                         ^

RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at run (/Users/ericnakagawa/Work/Docusaurus/node_modules/decache/decache.js:63:26)
    at /Users/ericnakagawa/Work/Docusaurus/node_modules/decache/decache.js:64:17
    at Array.forEach (<anonymous>)
    at run (/Users/ericnakagawa/Work/Docusaurus/node_modules/decache/decache.js:63:26)
    at /Users/ericnakagawa/Work/Docusaurus/node_modules/decache/decache.js:64:17
    at Array.forEach (<anonymous>)
    at run (/Users/ericnakagawa/Work/Docusaurus/node_modules/decache/decache.js:63:26)
    at /Users/ericnakagawa/Work/Docusaurus/node_modules/decache/decache.js:64:17
    at Array.forEach (<anonymous>)
error Command failed with exit code 1.

**Comment by stoikerty** [comment]
I can confirm this is happening, I get the same error.

Node version: v8.4.0
NPM version: 5.3.0
```
RangeError: Maximum call stack size exceeded
    at Array.forEach (<anonymous>)
    at run (...my_project/node_modules/decache/decache.js:63:26)
    at ...my_project/node_modules/decache/decache.js:64:17
    at Array.forEach (<anonymous>)
    at run (...my_project/node_modules/decache/decache.js:63:26)
    at ...my_project/node_modules/decache/decache.js:64:17
    at Array.forEach (<anonymous>)
    at run (...my_project/node_modules/decache/decache.js:63:26)
    at ...my_project/node_modules/decache/decache.js:64:17
    at Array.forEach (<anonymous>)
```

**Comment by nelsonic** [comment]
@ericnakagawa _thank you_ for _opening_ this issue to report this! 🥇 
@stoikerty thanks for confirming bug report. 🏅 

do you see this error _every_ time you attempt to use `decache` with node v8.4.0 
or is there a _specific_ circumstance where it is the case?

**Comment by boaz-amit** [comment]
Getting a similar error with the latest Node version, 9.4.0. NPM is version 5.6.0 and decache is 4.3.0
